// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: messages/rosrelaypb/rosrelay.proto

package rosrelaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_MSG_TYPE_ERROR_RESPONSE             MsgType = 0
	MsgType_MSG_TYPE_ROS_TOPIC_PUBLISH_REQUEST  MsgType = 400
	MsgType_MSG_TYPE_ROS_TOPIC_PUBLISH_RESPONSE MsgType = 401
	MsgType_MSG_TYPE_ROS_TOPIC_BROADCAST        MsgType = 402
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:   "MSG_TYPE_ERROR_RESPONSE",
		400: "MSG_TYPE_ROS_TOPIC_PUBLISH_REQUEST",
		401: "MSG_TYPE_ROS_TOPIC_PUBLISH_RESPONSE",
		402: "MSG_TYPE_ROS_TOPIC_BROADCAST",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_ERROR_RESPONSE":             0,
		"MSG_TYPE_ROS_TOPIC_PUBLISH_REQUEST":  400,
		"MSG_TYPE_ROS_TOPIC_PUBLISH_RESPONSE": 401,
		"MSG_TYPE_ROS_TOPIC_BROADCAST":        402,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_rosrelaypb_rosrelay_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_messages_rosrelaypb_rosrelay_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_messages_rosrelaypb_rosrelay_proto_rawDescGZIP(), []int{0}
}

// RosTopicPublishRequest is sent by a client to publish a ROS2 topic message
// through the relay session. The relay treats the payload as opaque bytes —
// no parsing, validation, or schema awareness.
type RosTopicPublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the message.
	Type MsgType `protobuf:"varint,1,opt,name=type,proto3,enum=rosrelay.MsgType" json:"type,omitempty"`
	// The time the message is sent.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The id that identifies a request.
	RequestId uint32 `protobuf:"varint,1337,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The ROS2 topic name (e.g. "/cmd_vel", "/odom").
	Topic string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	// The ROS2 message type (e.g. "geometry_msgs/msg/Twist",
	// "sensor_msgs/msg/CompressedImage").
	RosMessageType string `protobuf:"bytes,4,opt,name=ros_message_type,json=rosMessageType,proto3" json:"ros_message_type,omitempty"`
	// The opaque serialized ROS2 message payload (CDR or client's choice).
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional targeted delivery. When set, the relay forwards only to these
	// participant IDs. When empty, the relay fans out to all other session
	// participants.
	ParticipantIds []uint32 `protobuf:"varint,6,rep,packed,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RosTopicPublishRequest) Reset() {
	*x = RosTopicPublishRequest{}
	mi := &file_messages_rosrelaypb_rosrelay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RosTopicPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RosTopicPublishRequest) ProtoMessage() {}

func (x *RosTopicPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_rosrelaypb_rosrelay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RosTopicPublishRequest.ProtoReflect.Descriptor instead.
func (*RosTopicPublishRequest) Descriptor() ([]byte, []int) {
	return file_messages_rosrelaypb_rosrelay_proto_rawDescGZIP(), []int{0}
}

func (x *RosTopicPublishRequest) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_MSG_TYPE_ERROR_RESPONSE
}

func (x *RosTopicPublishRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RosTopicPublishRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RosTopicPublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RosTopicPublishRequest) GetRosMessageType() string {
	if x != nil {
		return x.RosMessageType
	}
	return ""
}

func (x *RosTopicPublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RosTopicPublishRequest) GetParticipantIds() []uint32 {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

// RosTopicPublishResponse is returned to the sender to acknowledge receipt.
type RosTopicPublishResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the message.
	Type MsgType `protobuf:"varint,1,opt,name=type,proto3,enum=rosrelay.MsgType" json:"type,omitempty"`
	// The time the message is sent.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The id that identifies a request.
	RequestId     uint32 `protobuf:"varint,1337,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RosTopicPublishResponse) Reset() {
	*x = RosTopicPublishResponse{}
	mi := &file_messages_rosrelaypb_rosrelay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RosTopicPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RosTopicPublishResponse) ProtoMessage() {}

func (x *RosTopicPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_rosrelaypb_rosrelay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RosTopicPublishResponse.ProtoReflect.Descriptor instead.
func (*RosTopicPublishResponse) Descriptor() ([]byte, []int) {
	return file_messages_rosrelaypb_rosrelay_proto_rawDescGZIP(), []int{1}
}

func (x *RosTopicPublishResponse) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_MSG_TYPE_ERROR_RESPONSE
}

func (x *RosTopicPublishResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RosTopicPublishResponse) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// RosTopicBroadcast is the message delivered to other session participants
// when a ROS2 topic message is published.
type RosTopicBroadcast struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the message.
	Type MsgType `protobuf:"varint,1,opt,name=type,proto3,enum=rosrelay.MsgType" json:"type,omitempty"`
	// The time the message is sent.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The timestamp of the request that triggered the broadcast.
	OriginTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=origin_timestamp,json=originTimestamp,proto3" json:"origin_timestamp,omitempty"`
	// The ROS2 topic name.
	Topic string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	// The ROS2 message type.
	RosMessageType string `protobuf:"bytes,5,opt,name=ros_message_type,json=rosMessageType,proto3" json:"ros_message_type,omitempty"`
	// The opaque serialized ROS2 message payload.
	Payload []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// The participant ID of the sender.
	OriginParticipantId uint32 `protobuf:"varint,7,opt,name=origin_participant_id,json=originParticipantId,proto3" json:"origin_participant_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RosTopicBroadcast) Reset() {
	*x = RosTopicBroadcast{}
	mi := &file_messages_rosrelaypb_rosrelay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RosTopicBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RosTopicBroadcast) ProtoMessage() {}

func (x *RosTopicBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_messages_rosrelaypb_rosrelay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RosTopicBroadcast.ProtoReflect.Descriptor instead.
func (*RosTopicBroadcast) Descriptor() ([]byte, []int) {
	return file_messages_rosrelaypb_rosrelay_proto_rawDescGZIP(), []int{2}
}

func (x *RosTopicBroadcast) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_MSG_TYPE_ERROR_RESPONSE
}

func (x *RosTopicBroadcast) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RosTopicBroadcast) GetOriginTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.OriginTimestamp
	}
	return nil
}

func (x *RosTopicBroadcast) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RosTopicBroadcast) GetRosMessageType() string {
	if x != nil {
		return x.RosMessageType
	}
	return ""
}

func (x *RosTopicBroadcast) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RosTopicBroadcast) GetOriginParticipantId() uint32 {
	if x != nil {
		return x.OriginParticipantId
	}
	return 0
}

var File_messages_rosrelaypb_rosrelay_proto protoreflect.FileDescriptor

const file_messages_rosrelaypb_rosrelay_proto_rawDesc = "" +
	"\n" +
	"\"messages/rosrelaypb/rosrelay.proto\x12\brosrelay\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x02\n" +
	"\x16RosTopicPublishRequest\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.rosrelay.MsgTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1e\n" +
	"\n" +
	"request_id\x18\xb9\n" +
	" \x01(\rR\trequestId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12(\n" +
	"\x10ros_message_type\x18\x04 \x01(\tR\x0erosMessageType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12'\n" +
	"\x0fparticipant_ids\x18\x06 \x03(\rR\x0eparticipantIds\"\x9a\x01\n" +
	"\x17RosTopicPublishResponse\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.rosrelay.MsgTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1e\n" +
	"\n" +
	"request_id\x18\xb9\n" +
	" \x01(\rR\trequestId\"\xc9\x02\n" +
	"\x11RosTopicBroadcast\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.rosrelay.MsgTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12E\n" +
	"\x10origin_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0foriginTimestamp\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12(\n" +
	"\x10ros_message_type\x18\x05 \x01(\tR\x0erosMessageType\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x122\n" +
	"\x15origin_participant_id\x18\a \x01(\rR\x13originParticipantId*\xae\x01\n" +
	"\aMsgType\x12\x1b\n" +
	"\x17MSG_TYPE_ERROR_RESPONSE\x10\x00\x12'\n" +
	"\"MSG_TYPE_ROS_TOPIC_PUBLISH_REQUEST\x10\x90\x03\x12(\n" +
	"#MSG_TYPE_ROS_TOPIC_PUBLISH_RESPONSE\x10\x91\x03\x12!\n" +
	"\x1cMSG_TYPE_ROS_TOPIC_BROADCAST\x10\x92\x03\"\x05\b\x01\x10\x8f\x03\"\t\b\xf4\x03\x10\xff\xff\xff\xff\aBHZ\x13messages/rosrelaypb\xa2\x02\bRosRelay\xaa\x02%Auki.ConjureKit.RosRelay.Protobuf.Genb\x06proto3"

var (
	file_messages_rosrelaypb_rosrelay_proto_rawDescOnce sync.Once
	file_messages_rosrelaypb_rosrelay_proto_rawDescData []byte
)

func file_messages_rosrelaypb_rosrelay_proto_rawDescGZIP() []byte {
	file_messages_rosrelaypb_rosrelay_proto_rawDescOnce.Do(func() {
		file_messages_rosrelaypb_rosrelay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_rosrelaypb_rosrelay_proto_rawDesc), len(file_messages_rosrelaypb_rosrelay_proto_rawDesc)))
	})
	return file_messages_rosrelaypb_rosrelay_proto_rawDescData
}

var file_messages_rosrelaypb_rosrelay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_rosrelaypb_rosrelay_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_messages_rosrelaypb_rosrelay_proto_goTypes = []any{
	(MsgType)(0),                    // 0: rosrelay.MsgType
	(*RosTopicPublishRequest)(nil),  // 1: rosrelay.RosTopicPublishRequest
	(*RosTopicPublishResponse)(nil), // 2: rosrelay.RosTopicPublishResponse
	(*RosTopicBroadcast)(nil),       // 3: rosrelay.RosTopicBroadcast
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_messages_rosrelaypb_rosrelay_proto_depIdxs = []int32{
	0, // 0: rosrelay.RosTopicPublishRequest.type:type_name -> rosrelay.MsgType
	4, // 1: rosrelay.RosTopicPublishRequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: rosrelay.RosTopicPublishResponse.type:type_name -> rosrelay.MsgType
	4, // 3: rosrelay.RosTopicPublishResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 4: rosrelay.RosTopicBroadcast.type:type_name -> rosrelay.MsgType
	4, // 5: rosrelay.RosTopicBroadcast.timestamp:type_name -> google.protobuf.Timestamp
	4, // 6: rosrelay.RosTopicBroadcast.origin_timestamp:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_messages_rosrelaypb_rosrelay_proto_init() }
func file_messages_rosrelaypb_rosrelay_proto_init() {
	if File_messages_rosrelaypb_rosrelay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_rosrelaypb_rosrelay_proto_rawDesc), len(file_messages_rosrelaypb_rosrelay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_rosrelaypb_rosrelay_proto_goTypes,
		DependencyIndexes: file_messages_rosrelaypb_rosrelay_proto_depIdxs,
		EnumInfos:         file_messages_rosrelaypb_rosrelay_proto_enumTypes,
		MessageInfos:      file_messages_rosrelaypb_rosrelay_proto_msgTypes,
	}.Build()
	File_messages_rosrelaypb_rosrelay_proto = out.File
	file_messages_rosrelaypb_rosrelay_proto_goTypes = nil
	file_messages_rosrelaypb_rosrelay_proto_depIdxs = nil
}
