name: Tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: aukilabs/go-tooling/.github/workflows/tests.yml@feature/reusable-workflows
    name: Tests
    with:
      enable_coverage: true

